CREATE TABLE IF NOT EXISTS 
dsectrl ("id" INTEGER PRIMARY KEY AUTOINCREMENT, 
"time" DEFAULT CURRENT_TIMESTAMP NOT NULL, 
"tuerkontakt" INTEGER NOT NULL, 
"rpmgeblaese" INTEGER NOT NULL, 
"tempkessel" INTEGER NOT NULL, 
"temprueckl" INTEGER NOT NULL, 
"pufferunten" INTEGER NOT NULL, 
"puffermitte" INTEGER NOT NULL, 
"pufferoben" INTEGER NOT NULL, 
"tempabgas" INTEGER NOT NULL, 
"luftoben" INTEGER NOT NULL, 
"luftunten" INTEGER NOT NULL, 
"031unknown" INTEGER NOT NULL, 
"evtltagnach" INTEGER NOT NULL, 
"evtlpumpemk1" INTEGER NOT NULL, 
"tempaussen" INTEGER NOT NULL, 
"ladungpuffer" INTEGER NOT NULL, 
"076unknown" INTEGER NOT NULL, 
"197unknown" INTEGER NOT NULL, 
"198unknown" INTEGER NOT NULL, 
"212unknown" INTEGER NOT NULL);
