CREATE TABLE IF NOT EXISTS
data ("id"                   INTEGER PRIMARY KEY AUTOINCREMENT,
    "time"                 DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "system_time"          TEXT NOT NULL,
    "003_0_bei_Tuer_offen" INTEGER NOT NULL,
    "007_RpmGeblaese"      INTEGER NOT NULL,
    "008_TempKessel"       INTEGER NOT NULL,
    "009 TempRueckl"       INTEGER NOT NULL,
    "010_PufferUnten"      INTEGER NOT NULL,
    "011_PufferMitte"      INTEGER NOT NULL,
    "012_PufferOben"       INTEGER NOT NULL,
    "015_TempAbgas"        INTEGER NOT NULL,
    "016_LuftOben"         INTEGER NOT NULL,
    "017_LuftUnten"        INTEGER NOT NULL,
    "031_unknown"          INTEGER NOT NULL,
    "039_TagNacht_evtl"    INTEGER NOT NULL,
    "043_Pumpe_MK1_evtl"   INTEGER NOT NULL,
    "068_Vorlauf_MK1"      INTEGER NOT NULL,
    "070_TempAussen"       INTEGER NOT NULL,
    "075_Pufferladung"     INTEGER NOT NULL,
    "076_unknown"          INTEGER NOT NULL,
    "197_unknown"          INTEGER NOT NULL,
    "198_unknown"          INTEGER NOT NULL,
    "212_unknown"          INTEGER NOT NULL);
